name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install clang
      run: sudo apt-get update && sudo apt-get install -y clang-14
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        #    - name: Lint with flake8
        #run: |
        #source env.sh
        ## stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        ## exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ## flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: UnitTest with pytest
      run: |
        source env.sh
        cd asdl/lang/cpp
        pytest
